# Generated by Django 3.2.20 on 2023-07-24 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='due',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='due',
            name='payment_history',
        ),
        migrations.AlterField(
            model_name='due',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='due',
            name='remaining_money',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='due',
            name='total_money',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='DuePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pay_date', models.DateTimeField()),
                ('total_money', models.FloatField()),
                ('payment_detail', models.CharField(blank=True, max_length=500, null=True)),
                ('due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_of_payment', to='shop_admin.due')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DueDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField()),
                ('total_money', models.FloatField()),
                ('due_detail', models.CharField(blank=True, max_length=500, null=True)),
                ('due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_of_due_history', to='shop_admin.due')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='due',
            name='due_history',
            field=models.ManyToManyField(related_name='due_history', to='shop_admin.DueDetail'),
        ),
        migrations.AddField(
            model_name='due',
            name='payment_history',
            field=models.ManyToManyField(related_name='due_payment_history', to='shop_admin.DuePayment'),
        ),
    ]
