# Generated by Django 3.2.20 on 2023-12-01 03:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCategory',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('category_type', models.CharField(choices=[('PER_KG', 'PER_KG'), ('PER_LTR', 'PER_LTR'), ('PER_PIECE', 'PER_PIECE')], max_length=15)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'unique_together': {('category_type', 'name')},
            },
        ),
    ]
