# Generated by Django 3.2.20 on 2023-12-03 09:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('total', models.FloatField(default=0)),
                ('category_type', models.CharField(choices=[('PER_KG', 'PER_KG'), ('PER_LTR', 'PER_LTR'), ('PER_PIECE', 'PER_PIECE')], max_length=15)),
                ('price', models.FloatField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_category_items', to='category.customcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
